# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
package(
    default_visibility = [
        "//visibility:public",
    ],
)

load("//build/bazel_common_rules/dist:dist.bzl", "copy_to_dist_dir")
load("//build/kernel/kleaf:common_kernels.bzl", "define_common_kernels", "define_db845c")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers", "kernel_build")

_aarch64_additional_kmi_symbol_lists = [
    # keep sorted
    "android/abi_gki_aarch64_db845c",
    "android/abi_gki_aarch64_exynos",
    "android/abi_gki_aarch64_pixel",
]

define_common_kernels(target_configs = {
    # Sync with build.config.gki.aarch64
    "kernel_aarch64": {
        # TODO(b/188620248): re-enable trimming
        "trim_nonlisted_kmi": False,
        "kmi_symbol_list_strict_mode": False,
        "module_implicit_outs": [
            "drivers/block/zram/zram.ko",
            "mm/zsmalloc.ko",
        ],
        "kmi_symbol_list": "android/abi_gki_aarch64",
        "additional_kmi_symbol_lists": _aarch64_additional_kmi_symbol_lists,
    },
    # Sync with build.config.gki.aarch64.16k
    "kernel_aarch64_16k": {
        "module_implicit_outs": [
            "drivers/block/zram/zram.ko",
            "mm/zsmalloc.ko",
        ],
    },
    # Sync with build.config.gki-debug.aarch64
    "kernel_aarch64_debug": {
        # TODO(b/188620248): re-enable trimming
        "trim_nonlisted_kmi": False,
        "kmi_symbol_list_strict_mode": False,
        "module_implicit_outs": [
            "drivers/block/zram/zram.ko",
            "mm/zsmalloc.ko",
        ],
        "kmi_symbol_list": "android/abi_gki_aarch64",
        "additional_kmi_symbol_lists": _aarch64_additional_kmi_symbol_lists,
    },
})

# Sync with build.config.db845c
define_db845c(
    name = "db845c",
    outs = [
        "arch/arm64/boot/dts/qcom/qrb5165-rb5.dtb",
        "arch/arm64/boot/dts/qcom/sdm845-db845c.dtb",
    ],
    module_outs = [
        # keep sorted
        "crypto/michael_mic.ko",
        "drivers/base/regmap/regmap-sdw.ko",
        "drivers/base/regmap/regmap-slimbus.ko",
        "drivers/bus/mhi/core/mhi.ko",
        "drivers/clk/qcom/clk-qcom.ko",
        "drivers/clk/qcom/clk-rpmh.ko",
        "drivers/clk/qcom/clk-spmi-pmic-div.ko",
        "drivers/clk/qcom/dispcc-sdm845.ko",
        "drivers/clk/qcom/dispcc-sm8250.ko",
        "drivers/clk/qcom/gcc-sdm845.ko",
        "drivers/clk/qcom/gcc-sm8250.ko",
        "drivers/clk/qcom/gpucc-sdm845.ko",
        "drivers/clk/qcom/gpucc-sm8250.ko",
        "drivers/clk/qcom/lpass-gfm-sm8250.ko",
        "drivers/clk/qcom/videocc-sdm845.ko",
        "drivers/clk/qcom/videocc-sm8250.ko",
        "drivers/cpufreq/qcom-cpufreq-hw.ko",
        "drivers/dma-buf/heaps/system_heap.ko",
        "drivers/dma/qcom/bam_dma.ko",
        "drivers/extcon/extcon-usb-gpio.ko",
        "drivers/firmware/qcom-scm.ko",
        "drivers/gpio/gpio-wcd934x.ko",
        "drivers/gpu/drm/bridge/display-connector.ko",
        "drivers/gpu/drm/bridge/lontium-lt9611.ko",
        "drivers/gpu/drm/bridge/lontium-lt9611uxc.ko",
        "drivers/gpu/drm/msm/msm.ko",
        "drivers/gpu/drm/scheduler/gpu-sched.ko",
        "drivers/hwspinlock/qcom_hwspinlock.ko",
        "drivers/i2c/busses/i2c-designware-core.ko",
        "drivers/i2c/busses/i2c-designware-platform.ko",
        "drivers/i2c/busses/i2c-qcom-geni.ko",
        "drivers/i2c/busses/i2c-qup.ko",
        "drivers/i2c/busses/i2c-rk3x.ko",
        "drivers/i2c/i2c-dev.ko",
        "drivers/i2c/i2c-mux.ko",
        "drivers/i2c/muxes/i2c-mux-pca954x.ko",
        "drivers/iio/adc/qcom-spmi-adc5.ko",
        "drivers/iio/adc/qcom-vadc-common.ko",
        "drivers/input/misc/pm8941-pwrkey.ko",
        "drivers/interconnect/qcom/icc-bcm-voter.ko",
        "drivers/interconnect/qcom/icc-osm-l3.ko",
        "drivers/interconnect/qcom/icc-rpmh.ko",
        "drivers/interconnect/qcom/qnoc-sdm845.ko",
        "drivers/interconnect/qcom/qnoc-sm8250.ko",
        "drivers/iommu/arm/arm-smmu/arm_smmu.ko",
        "drivers/irqchip/qcom-pdc.ko",
        "drivers/leds/led-class-multicolor.ko",
        "drivers/mailbox/qcom-apcs-ipc-mailbox.ko",
        "drivers/mailbox/qcom-ipcc.ko",
        "drivers/mfd/qcom-spmi-pmic.ko",
        "drivers/mfd/wcd934x.ko",
        "drivers/misc/fastrpc.ko",
        "drivers/mmc/host/cqhci.ko",
        "drivers/mmc/host/sdhci-msm.ko",
        "drivers/net/can/spi/mcp251xfd/mcp251xfd.ko",
        "drivers/net/wireless/ath/ath.ko",
        "drivers/net/wireless/ath/ath10k/ath10k_core.ko",
        "drivers/net/wireless/ath/ath10k/ath10k_pci.ko",
        "drivers/net/wireless/ath/ath10k/ath10k_snoc.ko",
        "drivers/net/wireless/ath/ath11k/ath11k.ko",
        "drivers/net/wireless/ath/ath11k/ath11k_ahb.ko",
        "drivers/net/wireless/ath/ath11k/ath11k_pci.ko",
        "drivers/nvmem/nvmem_qfprom.ko",
        "drivers/phy/qualcomm/phy-qcom-qmp.ko",
        "drivers/phy/qualcomm/phy-qcom-qusb2.ko",
        "drivers/phy/qualcomm/phy-qcom-snps-femto-v2.ko",
        "drivers/phy/qualcomm/phy-qcom-usb-hs.ko",
        "drivers/pinctrl/qcom/pinctrl-lpass-lpi.ko",
        "drivers/pinctrl/qcom/pinctrl-msm.ko",
        "drivers/pinctrl/qcom/pinctrl-sdm845.ko",
        "drivers/pinctrl/qcom/pinctrl-sm8250.ko",
        "drivers/pinctrl/qcom/pinctrl-spmi-gpio.ko",
        "drivers/pinctrl/qcom/pinctrl-spmi-mpp.ko",
        "drivers/power/reset/qcom-pon.ko",
        "drivers/power/reset/reboot-mode.ko",
        "drivers/power/reset/syscon-reboot-mode.ko",
        "drivers/regulator/gpio-regulator.ko",
        "drivers/regulator/qcom-rpmh-regulator.ko",
        "drivers/regulator/qcom_spmi-regulator.ko",
        "drivers/regulator/qcom_usb_vbus-regulator.ko",
        "drivers/remoteproc/qcom_common.ko",
        "drivers/remoteproc/qcom_pil_info.ko",
        "drivers/remoteproc/qcom_q6v5.ko",
        "drivers/remoteproc/qcom_q6v5_adsp.ko",
        "drivers/remoteproc/qcom_q6v5_mss.ko",
        "drivers/remoteproc/qcom_q6v5_pas.ko",
        "drivers/remoteproc/qcom_q6v5_wcss.ko",
        "drivers/remoteproc/qcom_sysmon.ko",
        "drivers/reset/reset-qcom-aoss.ko",
        "drivers/reset/reset-qcom-pdc.ko",
        "drivers/rpmsg/qcom_glink.ko",
        "drivers/rpmsg/qcom_glink_rpm.ko",
        "drivers/rpmsg/qcom_glink_smem.ko",
        "drivers/rpmsg/qcom_smd.ko",
        "drivers/rpmsg/rpmsg_ns.ko",
        "drivers/rtc/rtc-pm8xxx.ko",
        "drivers/slimbus/slim-qcom-ngd-ctrl.ko",
        "drivers/slimbus/slimbus.ko",
        "drivers/soc/qcom/apr.ko",
        "drivers/soc/qcom/cmd-db.ko",
        "drivers/soc/qcom/llcc-qcom.ko",
        "drivers/soc/qcom/mdt_loader.ko",
        "drivers/soc/qcom/pdr_interface.ko",
        "drivers/soc/qcom/qcom_aoss.ko",
        "drivers/soc/qcom/qcom_rpmh.ko",
        "drivers/soc/qcom/qmi_helpers.ko",
        "drivers/soc/qcom/rmtfs_mem.ko",
        "drivers/soc/qcom/rpmhpd.ko",
        "drivers/soc/qcom/smem.ko",
        "drivers/soc/qcom/smp2p.ko",
        "drivers/soc/qcom/smsm.ko",
        "drivers/soc/qcom/socinfo.ko",
        "drivers/soundwire/soundwire-bus.ko",
        "drivers/soundwire/soundwire-qcom.ko",
        "drivers/spi/spi-geni-qcom.ko",
        "drivers/spi/spi-pl022.ko",
        "drivers/spi/spi-qcom-qspi.ko",
        "drivers/spi/spi-qup.ko",
        "drivers/spmi/spmi-pmic-arb.ko",
        "drivers/thermal/qcom/lmh.ko",
        "drivers/thermal/qcom/qcom-spmi-adc-tm5.ko",
        "drivers/thermal/qcom/qcom-spmi-temp-alarm.ko",
        "drivers/thermal/qcom/qcom_tsens.ko",
        "drivers/tty/serial/msm_serial.ko",
        "drivers/ufs/host/ufs_qcom.ko",
        "drivers/usb/common/ulpi.ko",
        "drivers/usb/host/ohci-hcd.ko",
        "drivers/usb/host/ohci-pci.ko",
        "drivers/usb/host/ohci-platform.ko",
        "drivers/usb/typec/qcom-pmic-typec.ko",
        "drivers/watchdog/pm8916_wdt.ko",
        "drivers/watchdog/qcom-wdt.ko",
        "net/mac80211/mac80211.ko",
        "net/qrtr/ns.ko",
        "net/qrtr/qrtr.ko",
        "net/qrtr/qrtr-mhi.ko",
        "net/qrtr/qrtr-smd.ko",
        "net/qrtr/qrtr-tun.ko",
        "net/wireless/cfg80211.ko",
        "sound/soc/codecs/snd-soc-dmic.ko",
        "sound/soc/codecs/snd-soc-hdmi-codec.ko",
        "sound/soc/codecs/snd-soc-lpass-va-macro.ko",
        "sound/soc/codecs/snd-soc-lpass-wsa-macro.ko",
        "sound/soc/codecs/snd-soc-max98927.ko",
        "sound/soc/codecs/snd-soc-rl6231.ko",
        "sound/soc/codecs/snd-soc-rt5663.ko",
        "sound/soc/codecs/snd-soc-wcd-mbhc.ko",
        "sound/soc/codecs/snd-soc-wcd9335.ko",
        "sound/soc/codecs/snd-soc-wcd934x.ko",
        "sound/soc/codecs/snd-soc-wsa881x.ko",
        "sound/soc/qcom/qdsp6/q6adm.ko",
        "sound/soc/qcom/qdsp6/q6afe.ko",
        "sound/soc/qcom/qdsp6/q6afe-clocks.ko",
        "sound/soc/qcom/qdsp6/q6afe-dai.ko",
        "sound/soc/qcom/qdsp6/q6asm.ko",
        "sound/soc/qcom/qdsp6/q6asm-dai.ko",
        "sound/soc/qcom/qdsp6/q6core.ko",
        "sound/soc/qcom/qdsp6/q6dsp-common.ko",
        "sound/soc/qcom/qdsp6/q6routing.ko",
        "sound/soc/qcom/snd-soc-qcom-common.ko",
        "sound/soc/qcom/snd-soc-sdm845.ko",
        "sound/soc/qcom/snd-soc-sm8250.ko",
    ],
)

kernel_build(
    name = "fips140",
    outs = [],
    base_kernel = ":kernel_aarch64",
    build_config = "build.config.gki.aarch64.fips140",
    module_outs = ["crypto/fips140.ko"],
)

copy_to_dist_dir(
    name = "fips140_dist",
    data = [
        ":fips140",
    ],
    dist_dir = "out/fips140/dist",
    flat = True,
)

# DDK Headers
# DDK headers allowlist. This is the list of all headers and include
# directories that are safe to use in DDK modules.
ddk_headers(
    name = "all_headers",
    hdrs = [
        "include/acpi/acbuffer.h",
        "include/acpi/acconfig.h",
        "include/acpi/acexcep.h",
        "include/acpi/acnames.h",
        "include/acpi/acoutput.h",
        "include/acpi/acpi.h",
        "include/acpi/acpi_numa.h",
        "include/acpi/acpiosxf.h",
        "include/acpi/acpixf.h",
        "include/acpi/acrestyp.h",
        "include/acpi/actbl.h",
        "include/acpi/actbl1.h",
        "include/acpi/actbl2.h",
        "include/acpi/actbl3.h",
        "include/acpi/actypes.h",
        "include/acpi/apei.h",
        "include/acpi/ghes.h",
        "include/acpi/hed.h",
        "include/acpi/platform/acenv.h",
        "include/acpi/platform/acenvex.h",
        "include/acpi/platform/acgcc.h",
        "include/acpi/platform/acgccex.h",
        "include/acpi/platform/aclinux.h",
        "include/acpi/platform/aclinuxex.h",
        "include/clocksource/arm_arch_timer.h",
        "include/crypto/aead.h",
        "include/crypto/aes.h",
        "include/crypto/algapi.h",
        "include/crypto/arc4.h",
        "include/crypto/hash.h",
        "include/crypto/hash_info.h",
        "include/crypto/md5.h",
        "include/crypto/sha1.h",
        "include/crypto/sha2.h",
        "include/crypto/skcipher.h",
        "include/crypto/streebog.h",
        "include/drm/drm_atomic.h",
        "include/drm/drm_atomic_helper.h",
        "include/drm/drm_atomic_state_helper.h",
        "include/drm/drm_atomic_uapi.h",
        "include/drm/drm_blend.h",
        "include/drm/drm_bridge.h",
        "include/drm/drm_client.h",
        "include/drm/drm_color_mgmt.h",
        "include/drm/drm_connector.h",
        "include/drm/drm_crtc.h",
        "include/drm/drm_crtc_helper.h",
        "include/drm/drm_debugfs_crc.h",
        "include/drm/drm_device.h",
        "include/drm/drm_dp_helper.h",
        "include/drm/drm_drv.h",
        "include/drm/drm_dsc.h",
        "include/drm/drm_edid.h",
        "include/drm/drm_encoder.h",
        "include/drm/drm_fb_helper.h",
        "include/drm/drm_file.h",
        "include/drm/drm_fourcc.h",
        "include/drm/drm_framebuffer.h",
        "include/drm/drm_gem.h",
        "include/drm/drm_gem_framebuffer_helper.h",
        "include/drm/drm_hashtab.h",
        "include/drm/drm_ioctl.h",
        "include/drm/drm_lease.h",
        "include/drm/drm_managed.h",
        "include/drm/drm_mipi_dsi.h",
        "include/drm/drm_mm.h",
        "include/drm/drm_mode_config.h",
        "include/drm/drm_mode_object.h",
        "include/drm/drm_modes.h",
        "include/drm/drm_modeset_helper.h",
        "include/drm/drm_modeset_helper_vtables.h",
        "include/drm/drm_modeset_lock.h",
        "include/drm/drm_of.h",
        "include/drm/drm_panel.h",
        "include/drm/drm_plane.h",
        "include/drm/drm_plane_helper.h",
        "include/drm/drm_prime.h",
        "include/drm/drm_print.h",
        "include/drm/drm_probe_helper.h",
        "include/drm/drm_property.h",
        "include/drm/drm_rect.h",
        "include/drm/drm_self_refresh_helper.h",
        "include/drm/drm_util.h",
        "include/drm/drm_vblank.h",
        "include/drm/drm_vma_manager.h",
        "include/drm/drm_writeback.h",
        "include/dt-bindings/leds/common.h",
        "include/dt-bindings/pinctrl/samsung.h",
        "include/kvm/arm_arch_timer.h",
        "include/kvm/arm_hypercalls.h",
        "include/kvm/arm_pmu.h",
        "include/kvm/arm_psci.h",
        "include/kvm/arm_vgic.h",
        "include/kvm/iodev.h",
        "include/media/frame_vector.h",
        "include/media/hevc-ctrls.h",
        "include/media/media-device.h",
        "include/media/media-devnode.h",
        "include/media/media-entity.h",
        "include/media/media-request.h",
        "include/media/v4l2-async.h",
        "include/media/v4l2-common.h",
        "include/media/v4l2-ctrls.h",
        "include/media/v4l2-dev.h",
        "include/media/v4l2-device.h",
        "include/media/v4l2-fh.h",
        "include/media/v4l2-ioctl.h",
        "include/media/v4l2-mediabus.h",
        "include/media/v4l2-mem2mem.h",
        "include/media/v4l2-subdev.h",
        "include/media/videobuf2-core.h",
        "include/media/videobuf2-dma-sg.h",
        "include/media/videobuf2-v4l2.h",
        "include/media/videobuf2-vmalloc.h",
        "include/net/addrconf.h",
        "include/net/af_ieee802154.h",
        "include/net/arp.h",
        "include/net/cfg80211.h",
        "include/net/cfg80211-wext.h",
        "include/net/cfg802154.h",
        "include/net/checksum.h",
        "include/net/codel.h",
        "include/net/codel_impl.h",
        "include/net/dsfield.h",
        "include/net/dst.h",
        "include/net/dst_ops.h",
        "include/net/fib_notifier.h",
        "include/net/fib_rules.h",
        "include/net/flow.h",
        "include/net/flow_dissector.h",
        "include/net/flow_offload.h",
        "include/net/fq.h",
        "include/net/fq_impl.h",
        "include/net/gen_stats.h",
        "include/net/genetlink.h",
        "include/net/gro_cells.h",
        "include/net/ieee80211_radiotap.h",
        "include/net/if_inet6.h",
        "include/net/inet_connection_sock.h",
        "include/net/inet_ecn.h",
        "include/net/inet_frag.h",
        "include/net/inet_hashtables.h",
        "include/net/inet_sock.h",
        "include/net/inet_timewait_sock.h",
        "include/net/inetpeer.h",
        "include/net/ip.h",
        "include/net/ip6_checksum.h",
        "include/net/ip6_fib.h",
        "include/net/ip_fib.h",
        "include/net/ipv6.h",
        "include/net/ipv6_stubs.h",
        "include/net/iw_handler.h",
        "include/net/l3mdev.h",
        "include/net/lib80211.h",
        "include/net/lwtunnel.h",
        "include/net/mac80211.h",
        "include/net/mac802154.h",
        "include/net/mptcp.h",
        "include/net/ndisc.h",
        "include/net/neighbour.h",
        "include/net/net_namespace.h",
        "include/net/netlink.h",
        "include/net/netns/bpf.h",
        "include/net/netns/can.h",
        "include/net/netns/conntrack.h",
        "include/net/netns/core.h",
        "include/net/netns/generic.h",
        "include/net/netns/hash.h",
        "include/net/netns/ieee802154_6lowpan.h",
        "include/net/netns/ipv4.h",
        "include/net/netns/ipv6.h",
        "include/net/netns/mctp.h",
        "include/net/netns/mib.h",
        "include/net/netns/mpls.h",
        "include/net/netns/netfilter.h",
        "include/net/netns/nexthop.h",
        "include/net/netns/nftables.h",
        "include/net/netns/packet.h",
        "include/net/netns/sctp.h",
        "include/net/netns/smc.h",
        "include/net/netns/unix.h",
        "include/net/netns/xdp.h",
        "include/net/netns/xfrm.h",
        "include/net/netprio_cgroup.h",
        "include/net/nfc/nci.h",
        "include/net/nfc/nfc.h",
        "include/net/nl802154.h",
        "include/net/page_pool.h",
        "include/net/pkt_sched.h",
        "include/net/regulatory.h",
        "include/net/request_sock.h",
        "include/net/route.h",
        "include/net/rtnetlink.h",
        "include/net/sch_generic.h",
        "include/net/scm.h",
        "include/net/snmp.h",
        "include/net/sock.h",
        "include/net/sock_reuseport.h",
        "include/net/tcp.h",
        "include/net/tcp_states.h",
        "include/net/timewait_sock.h",
        "include/net/udp.h",
        "include/net/xdp.h",
        "include/net/xfrm.h",
        "include/scsi/scsi.h",
        "include/scsi/scsi_cmnd.h",
        "include/scsi/scsi_common.h",
        "include/scsi/scsi_dbg.h",
        "include/scsi/scsi_device.h",
        "include/scsi/scsi_driver.h",
        "include/scsi/scsi_eh.h",
        "include/scsi/scsi_host.h",
        "include/scsi/scsi_ioctl.h",
        "include/scsi/scsi_proto.h",
        "include/scsi/scsi_request.h",
        "include/scsi/scsi_status.h",
        "include/scsi/scsi_tcq.h",
        "include/scsi/sg.h",
        "include/sound/ac97/regs.h",
        "include/sound/ac97_codec.h",
        "include/sound/asound.h",
        "include/sound/compress_driver.h",
        "include/sound/control.h",
        "include/sound/core.h",
        "include/sound/info.h",
        "include/sound/initval.h",
        "include/sound/jack.h",
        "include/sound/memalloc.h",
        "include/sound/minors.h",
        "include/sound/pcm.h",
        "include/sound/pcm_params.h",
        "include/sound/soc.h",
        "include/sound/soc-card.h",
        "include/sound/soc-component.h",
        "include/sound/soc-dai.h",
        "include/sound/soc-dapm.h",
        "include/sound/soc-dpcm.h",
        "include/sound/soc-jack.h",
        "include/sound/soc-topology.h",
        "include/sound/tlv.h",
        "include/trace/bpf_probe.h",
        "include/trace/define_trace.h",
        "include/trace/events/gpu_mem.h",
        "include/trace/events/mmflags.h",
        "include/trace/events/napi.h",
        "include/trace/events/power.h",
        "include/trace/events/vmscan.h",
        "include/trace/hooks/bug.h",
        "include/trace/hooks/cpuidle.h",
        "include/trace/hooks/debug.h",
        "include/trace/hooks/mm.h",
        "include/trace/hooks/ufshcd.h",
        "include/trace/hooks/vendor_hooks.h",
        "include/trace/perf.h",
        "include/trace/syscall.h",
        "include/trace/trace_events.h",
        "include/uapi/asm-generic/bitsperlong.h",
        "include/uapi/asm-generic/errno.h",
        "include/uapi/asm-generic/errno-base.h",
        "include/uapi/asm-generic/fcntl.h",
        "include/uapi/asm-generic/hugetlb_encode.h",
        "include/uapi/asm-generic/int-ll64.h",
        "include/uapi/asm-generic/ioctl.h",
        "include/uapi/asm-generic/ioctls.h",
        "include/uapi/asm-generic/ipcbuf.h",
        "include/uapi/asm-generic/kvm_para.h",
        "include/uapi/asm-generic/mman.h",
        "include/uapi/asm-generic/mman-common.h",
        "include/uapi/asm-generic/param.h",
        "include/uapi/asm-generic/poll.h",
        "include/uapi/asm-generic/posix_types.h",
        "include/uapi/asm-generic/resource.h",
        "include/uapi/asm-generic/sembuf.h",
        "include/uapi/asm-generic/shmbuf.h",
        "include/uapi/asm-generic/siginfo.h",
        "include/uapi/asm-generic/signal.h",
        "include/uapi/asm-generic/signal-defs.h",
        "include/uapi/asm-generic/socket.h",
        "include/uapi/asm-generic/sockios.h",
        "include/uapi/asm-generic/stat.h",
        "include/uapi/asm-generic/swab.h",
        "include/uapi/asm-generic/termbits.h",
        "include/uapi/asm-generic/termios.h",
        "include/uapi/asm-generic/types.h",
        "include/uapi/asm-generic/unistd.h",
        "include/uapi/drm/drm.h",
        "include/uapi/drm/drm_fourcc.h",
        "include/uapi/drm/drm_mode.h",
        "include/uapi/drm/exynos_drm.h",
        "include/uapi/scsi/scsi_bsg_ufs.h",
        "include/uapi/sound/asoc.h",
        "include/uapi/sound/asound.h",
        "include/uapi/sound/compress_offload.h",
        "include/uapi/sound/compress_params.h",
        "include/uapi/sound/tlv.h",
        "include/vdso/bits.h",
        "include/vdso/clocksource.h",
        "include/vdso/const.h",
        "include/vdso/datapage.h",
        "include/vdso/helpers.h",
        "include/vdso/jiffies.h",
        "include/vdso/ktime.h",
        "include/vdso/limits.h",
        "include/vdso/math64.h",
        "include/vdso/processor.h",
        "include/vdso/time.h",
        "include/vdso/time32.h",
        "include/vdso/time64.h",
        "include/video/display_timing.h",
        "include/video/mipi_display.h",
        "include/video/videomode.h",
        ":all_headers_globs",
    ],
    includes = [
        "arch/arm64/include",
        "arch/arm64/include/uapi",
        "include",
        "include/uapi",
    ],
    visibility = ["//visibility:public"],
)

# DDK headers unsafe list. This is the list of all headers and include
# directories that may be used during migration from kernel_module's, but
# should be avoided in general.
# Use with caution; items may:
# - be removed without notice
# - be moved into all_headers
ddk_headers(
    name = "all_headers_unsafe",
    hdrs = [
        "arch/arm64/kernel/image.h",
        "arch/arm64/kernel/image-vars.h",
        "arch/arm64/kvm/hyp/include/hyp/adjust_pc.h",
        "arch/arm64/kvm/hyp/include/hyp/debug-sr.h",
        "arch/arm64/kvm/hyp/include/hyp/fault.h",
        "arch/arm64/kvm/hyp/include/hyp/switch.h",
        "arch/arm64/kvm/hyp/include/hyp/sysreg-sr.h",
        "arch/arm64/kvm/hyp/include/nvhe/early_alloc.h",
        "arch/arm64/kvm/hyp/include/nvhe/ffa.h",
        "arch/arm64/kvm/hyp/include/nvhe/gfp.h",
        "arch/arm64/kvm/hyp/include/nvhe/iommu.h",
        "arch/arm64/kvm/hyp/include/nvhe/mem_protect.h",
        "arch/arm64/kvm/hyp/include/nvhe/memory.h",
        "arch/arm64/kvm/hyp/include/nvhe/mm.h",
        "arch/arm64/kvm/hyp/include/nvhe/pkvm.h",
        "arch/arm64/kvm/hyp/include/nvhe/spinlock.h",
        "arch/arm64/kvm/hyp/include/nvhe/trap_handler.h",
        "arch/arm64/kvm/sys_regs.h",
        "drivers/block/zram/zcomp.h",
        "drivers/block/zram/zram_drv.h",
        "drivers/devfreq/governor.h",
        "drivers/dma-buf/heaps/deferred-free-helper.h",
        "drivers/dma-buf/heaps/page_pool.h",
        "drivers/dma/dmaengine.h",
        "drivers/firmware/efi/libstub/efistub.h",
        "drivers/pci/controller/dwc/pcie-designware.h",
        "drivers/pinctrl/core.h",
        "drivers/pinctrl/samsung/pinctrl-samsung.h",
        "drivers/scsi/scsi.h",
        "drivers/scsi/scsi_logging.h",
        "drivers/scsi/ufs/ufs.h",
        "drivers/scsi/ufs/ufs_quirks.h",
        "drivers/scsi/ufs/ufshcd.h",
        "drivers/scsi/ufs/ufshcd-crypto.h",
        "drivers/scsi/ufs/ufshcd-pltfrm.h",
        "drivers/scsi/ufs/ufshci.h",
        "drivers/scsi/ufs/unipro.h",
        "drivers/staging/android/debug_kinfo.h",
        "drivers/thermal/thermal_core.h",
        "drivers/thermal/thermal_netlink.h",
        "drivers/usb/core/phy.h",
        "drivers/usb/dwc3/core.h",
        "drivers/usb/dwc3/debug.h",
        "drivers/usb/dwc3/gadget.h",
        "drivers/usb/dwc3/io.h",
        "drivers/usb/dwc3/trace.h",
        "drivers/usb/gadget/configfs.h",
        "drivers/usb/gadget/function/u_serial.h",
        "drivers/usb/host/pci-quirks.h",
        "drivers/usb/host/xhci.h",
        "drivers/usb/host/xhci-ext-caps.h",
        "drivers/usb/host/xhci-mvebu.h",
        "drivers/usb/host/xhci-plat.h",
        "drivers/usb/host/xhci-rcar.h",
        "drivers/usb/typec/tcpm/tcpci.h",
        "lib/kstrtox.h",
        "lib/vdso/gettimeofday.c",
        "lib/zlib_inflate/inffast.h",
        "lib/zlib_inflate/inflate.h",
        "lib/zlib_inflate/inftrees.h",
        "lib/zlib_inflate/infutil.h",
        "mm/internal.h",
    ],
    includes = [
        ".",
        "arch/arm64/kernel",
        "arch/arm64/kernel/vdso",
        "arch/arm64/kernel/vdso32",
        "arch/arm64/kvm",
        "arch/arm64/kvm/hyp/include",
        "arch/arm64/kvm/hyp/nvhe",
        "arch/arm64/lib",
        "drivers/block/zram",
        "drivers/devfreq",
        "drivers/dma",
        "drivers/dma-buf",
        "drivers/firmware/efi/libstub",
        "drivers/i2c",
        "drivers/misc/eeprom",
        "drivers/pci/controller/dwc",
        "drivers/perf",
        "drivers/pinctrl",
        "drivers/pps/clients",
        "drivers/scsi",
        "drivers/scsi/ufs",
        "drivers/spi",
        "drivers/thermal",
        "drivers/usb",
        "drivers/usb/gadget/function",
        "drivers/usb/typec",
        "drivers/watchdog",
        "lib",
        "mm",
    ],
    visibility = ["//visibility:public"],
)

# List of DDK headers allowlist that are glob()-ed to avoid changes of BUILD
# file when the list of files changes. All headers in these directories
# are safe to use.
filegroup(
    name = "all_headers_globs",
    srcs = glob([
        "arch/arm64/include/**/*.h",
        "include/asm-generic/**/*.h",
        "include/linux/**/*.h",
        "include/uapi/linux/**/*.h",
    ]),
    visibility = ["//visibility:private"],
)
