/* SPDX-License-Identifier: ((GPL-2.0 WITH Linux-syscall-note) OR BSD-3-Clause) */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/binder.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_ANDROID_BINDER_NETLINK_H
#define _UAPI_LINUX_ANDROID_BINDER_NETLINK_H

#define BINDER_FAMILY_NAME	"binder"
#define BINDER_FAMILY_VERSION	1

/*
 * Define what kind of binder transactions should be reported.
 */
enum binder_flag {
	BINDER_FLAG_FAILED = 1,
	BINDER_FLAG_ASYNC_FROZEN = 2,
	BINDER_FLAG_SPAM = 4,
	BINDER_FLAG_OVERRIDE = 8,
};

enum {
	BINDER_A_CMD_CONTEXT = 1,
	BINDER_A_CMD_PID,
	BINDER_A_CMD_FLAGS,

	__BINDER_A_CMD_MAX,
	BINDER_A_CMD_MAX = (__BINDER_A_CMD_MAX - 1)
};

enum {
	BINDER_A_REPORT_CONTEXT = 1,
	BINDER_A_REPORT_ERR,
	BINDER_A_REPORT_FROM_PID,
	BINDER_A_REPORT_FROM_TID,
	BINDER_A_REPORT_TO_PID,
	BINDER_A_REPORT_TO_TID,
	BINDER_A_REPORT_REPLY,
	BINDER_A_REPORT_FLAGS,
	BINDER_A_REPORT_CODE,
	BINDER_A_REPORT_DATA_SIZE,

	__BINDER_A_REPORT_MAX,
	BINDER_A_REPORT_MAX = (__BINDER_A_REPORT_MAX - 1)
};

enum {
	BINDER_CMD_REPORT_SETUP = 1,
	BINDER_CMD_REPORT,

	__BINDER_CMD_MAX,
	BINDER_CMD_MAX = (__BINDER_CMD_MAX - 1)
};

#define BINDER_MCGRP_REPORT	"report"

#endif /* _UAPI_LINUX_ANDROID_BINDER_NETLINK_H */
